### ISSUE TITLE
`lock` doesn't overwrite old PID with current PID

### ISSUE THREAD

**Issue by kevinswiber** [kesla/pidlockfile#1]
Given a lockfile exists
And its PID is no longer active,
When executing `lock`,
Then the old PID should be overwritten by the new PID.

That's currently failing.

**Comment by kesla** [comment]
Thanks, taking a look at it now.

**Comment by kesla** [comment]
Haha, oops. You're right. I fix.

**Comment by kevinswiber** [comment]
This fixes bugs I was seeing in [medea/medea](/medea/medea).  Very happy.  Thanks!
