### ISSUE TITLE
Ugly code - setting err inside if-condition

### ISSUE THREAD

**Issue by ozomer** [kesla/pidlockfile#5]
In line [24](https://github.com/kesla/pidlockfile/blob/master/pidlockfile.js#L24).

Instead, I suggest that lines 22-26 would be:

```
if (err) {
  if (err.code === 'ENOENT') {
    fs.writeFile(filename, pid, { flag: 'wx' }, callback)
  } else {
    callback(err)
  }
} else if (locked) {
  callback(new Error('Lockfile already acquired'))
} else {
```

**Comment by kesla** [comment]
I don't think this is ugly code. Ugly code, overall, is very subjective.

If you think that changing this would increase readability I'd gladly accept a PR, but as an issue I'll close this.
